targets = [ "//:gl2ps" ]

[[dependency]]
package = "github.com/buckaroo-pm/host-opengl"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/pkg-config-gl"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/freeglut"
version = "*"
